const blogs=[
    {
      id:1,
      title:"Building your API Stack",
      description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
      author:"Lana Steiner",
      date:"18 jan 2022",
      url:"https://developers.google.com/blogger/docs/3.0/using",
    },
    {
        id:2,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:3,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:4,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:5,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:6,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:7,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:8,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:9,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:10,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },{
        id:11,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
      {
        id:12,
        title:"Building your API Stack",
        description:"The rise of RESTful API's has been met by a rise in tools for creating, testing, and managing them. ",
        author:"Lana Steiner",
        date:"18 jan 2022",
        url:"https://developers.google.com/blogger/docs/3.0/using",
      },
]

export default blogs;