const jobs=[
    {
       company:"Innovative Solutions Inc",
       title:"Full Stack Developer",
       Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
       Location:"Remote",
       date:"15 May 2024",
       link:"#",
    },
    {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
     {
        company:"Innovative Solutions Inc",
        title:"Full Stack Developer",
        Description:"We are seeking a highly skilled and motivated Software Engineer to join our dynamic team. As a key member of our development team, you will be responsible for designing, developing, and maintaining scalable software solutions that meet the needs of our clients. This role offers an exciting opportunity to work on diverse projects, collaborate with talented professionals, and contribute to the success of our company.",
        Location:"Remote",
        date:"15 May 2024",
        link:"#",
     },
]

export default jobs;